services:
  expense-app:
    image: ghcr.io/tsaramaso/kl-expenses:latest
    container_name: expense-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8420:8420"
    env_file:
      - .env
    volumes:
      - ./data:/app/data