"""add is_active to operations

Revision ID: 5321e66c0ce1
Revises: 98ee7f5a555b
Create Date: 2026-07-28 14:53:47.385689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5321e66c0ce1"
down_revision: Union[str, Sequence[str], None] = "98ee7f5a555b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
