"""baseline

Revision ID: 98ee7f5a555b
Revises:
Create Date: 2026-07-28 13:04:35.358089

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "98ee7f5a555b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
