"""changes tablename

Revision ID: fc19b372d9e6
Revises: 5321e66c0ce1
Create Date: 2026-07-28 20:59:21.612966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc19b372d9e6"
down_revision: Union[str, Sequence[str], None] = "5321e66c0ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.String(length=36), nullable=False),
        sa.Column("related_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("income", "expense", name="directiontype"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum("kl", "home", "user", "other", name="categorytype"),
            nullable=False,
        ),
        sa.Column(
            "expense_type",
            sa.Enum(
                "groceries",
                "utilities",
                "other",
                "material",
                "food",
                "rent",
                "bill",
                "salary",
                "personal",
                "fuel",
                name="expensetype",
            ),
            nullable=True,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_user_uuid"],
            ["users.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("expenses")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_uuid", sa.VARCHAR(length=36), nullable=False),
        sa.Column("related_user_uuid", sa.VARCHAR(length=36), nullable=True),
        sa.Column("amount", sa.INTEGER(), nullable=False),
        sa.Column("direction", sa.VARCHAR(length=7), nullable=False),
        sa.Column("category", sa.VARCHAR(length=5), nullable=False),
        sa.Column("expense_type", sa.VARCHAR(length=9), nullable=True),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column(
            "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["related_user_uuid"],
            ["users.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("operations")
    # ### end Alembic commands ###
